version: '3.8'

services:
  # Redis RDI CTF - All-in-one container
  redis-rdi-ctf:
    build: .
    container_name: redis-rdi-ctf
    ports:
      - "5432:5432"   # PostgreSQL
      - "8080:8080"   # RDI Web UI
      - "3001:3001"   # SQLPad
    volumes:
      - ./labs:/app/labs
      - ./scripts:/app/scripts
      - ./.env:/app/.env
      - ctf_data:/var/lib/postgresql/14/main
    environment:
      - POSTGRES_USER=rdi_user
      - POSTGRES_PASSWORD=rdi_password
      - POSTGRES_DB=rdi_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rdi_user", "-d", "rdi_db", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Optional: Local Redis for testing (users can use Redis Cloud instead)
  # Start with: docker-compose --profile local-redis up
  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    profiles:
      - local-redis

volumes:
  ctf_data:
    driver: local
  redis_data:
    driver: local
