version: '3.8'

services:
  # PostgreSQL database (source for RDI)
  postgresql:
    image: postgres:15
    container_name: rdi-postgres-helm
    environment:
      POSTGRES_DB: chinook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - './postgresql.conf:/etc/postgresql/postgresql.conf'
      - './init-postgres-for-debezium.sql:/docker-entrypoint-initdb.d/01-init-debezium.sql'
      - './create_track_table.sql:/docker-entrypoint-initdb.d/02-create-track-table.sql'
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chinook"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RDI Helm container with K3s and Helm pre-installed
  rdi-helm:
    build:
      context: .
      dockerfile: rdi-helm.dockerfile
    container_name: rdi-helm
    privileged: true
    ports:
      - '2223:22'      # SSH access
      - '8445:443'     # RDI HTTPS port
      - '12003:12001'  # RDI API port
      - '13002:13000'  # Alternative RDI port
      - '8081:80'      # HTTP port for RDI UI
      - '6443:6443'    # K3s API server
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB=chinook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Default Redis Cloud connection (users can override)
      - REDIS_HOST=redis-17173.c14.us-east-1-2.ec2.redns.redis-cloud.com
      - REDIS_PORT=17173
      - REDIS_PASSWORD=redislabs
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/lib:/var/lib'
      - './rdi-config:/rdi-config'
    tmpfs:
      - /run
      - /tmp:exec,mode=1777
    depends_on:
      postgresql:
        condition: service_healthy

  # Redis Insight for monitoring
  redis-insight:
    image: redis/redisinsight:latest
    container_name: rdi-redis-insight-helm
    ports:
      - '5541:5540'
    volumes:
      - './redisinsight.db:/root/.redisinsight-v2-stage/redisinsight.db'

  # Web interface for lab instructions
  web-interface:
    image: httpd:2.4.63
    container_name: rdi-web-helm
    ports:
      - '8082:80'
    volumes:
      - './web:/usr/local/apache2/htdocs/'
      - './httpd.conf:/usr/local/apache2/conf/httpd.conf'

  # Log viewer
  dozzle:
    container_name: rdi-dozzle-helm
    image: 'amir20/dozzle:latest'
    ports:
      - '8083:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  redis-insight-data:
