version: '3.8'

services:
  postgresql:
    image: postgres:15.3-bullseye
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=chinook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./create_track_table.sql:/docker-entrypoint-initdb.d/create_track_table.sql
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - '5540:5540'
    volumes:
      - redisinsight-data:/data
    environment:
      - REDIS_INSIGHT_HOST=0.0.0.0
      - REDIS_INSIGHT_PORT=5540
    restart: unless-stopped

  rdi-cli:
    image: redis/rdi:latest
    container_name: rdi-cli
    volumes:
      - ./rdi-config:/config
    environment:
      - RDI_HOST=${RDI_HOST:-localhost}
      - RDI_PORT=${RDI_PORT:-13000}
      - RDI_PASSWORD=${RDI_PASSWORD:-}
    depends_on:
      - postgresql
    restart: unless-stopped
    command: tail -f /dev/null

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=redis-app,redis-datasource
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD:-redislabs}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana_config/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - '3000:3000'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    restart: unless-stopped

  sqlpad:
    image: sqlpad/sqlpad:6
    container_name: sqlpad
    ports:
      - '3001:3000'
    environment:
      SQLPAD_ADMIN: admin
      SQLPAD_ADMIN_PASSWORD: ${PASSWORD:-redislabs}
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__pgdemo__name: PostgreSQL-Source
      SQLPAD_CONNECTIONS__pgdemo__driver: postgres
      SQLPAD_CONNECTIONS__pgdemo__host: postgresql
      SQLPAD_CONNECTIONS__pgdemo__database: chinook
      SQLPAD_CONNECTIONS__pgdemo__username: postgres
      SQLPAD_CONNECTIONS__pgdemo__password: postgres
    depends_on:
      - postgresql
    restart: unless-stopped

volumes:
  postgres-data:
  redisinsight-data:
  grafana-data:

